### ISSUE TITLE
Lego Island Guy 

### ISSUE THREAD

**Issue by MrAppAndCrap** [itsmattkc/LEGO1Disassemble#1]
Hello LIG,
When is next video.
Thanks.

**Comment by JamesButBetter** [comment]
Hello LIG,
Please stop uploading videos.
I am trying to pay attention at some guys funeral.
Thanks.

**Comment by MrAppAndCrap** [comment]
> Hello LIG,
> Please stop uploading videos.
> I am trying to pay attention at some guys funeral.
> Thanks.

To fix this problem please announce loudly that you caught the LIG, Look concerned and start coughing, they will soon respect the power of the LIG. 

No LIG video or stream should ever be interrupted by a funeral.
